version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: uorriuart
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
